# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.1 on 2017-06-18 18:13
=======
# Generated by Django 1.11.3 on 2017-08-03 10:41
>>>>>>> 38e9ecd4eaae03ef4084980fa893f1aa5e42b94e
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='商品圖片'),
        ),
    ]
